### ISSUE TITLE
Production build error Supplied parameters do not match any signature of call target.

### ISSUE THREAD

**Issue by hengkyz** [swimlane/ngx-charts-dag#11]
BUG
im getting error when i try to user --prod environment
it is says 
"@swimlane/ngx-charts-dag/release/directed-graph/directed-graph.component.d.ts.DirectedGraphComponent.html (7,7): Supplied parameters do not match any signature of call target."

**Comment by amcdnl** [comment]
Please provide more implementation details or demo. I will reopen when that is done.

**Comment by Darkheir** [comment]
I have exactly the same problem.
Disabling aot (`ng build --prod --aot=false`) fixes the problem but this is just a temporary fix.

**Comment by Darkheir** [comment]
After a bit of investigation the problem comes from the following binding : `(legendLabelClick)="onClick($event)"`

The onClick method has the following definition that doesn't match the needed signature for an event:

```js
onClick(data, node): void {
  this.select.emit(data);
}


```

**Comment by amcdnl** [comment]
Can you PR this?

**Comment by Darkheir** [comment]
Yes ! Just a silly question, do I have to change only the src folder or also the release's one ?
