### ISSUE TITLE
Chart does not display correctly with Edge and IE 11

### ISSUE THREAD

**Issue by Gimly** [swimlane/ngx-charts-dag#12]
**I'm submitting a ...**
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
The graph from the demo has all the nodes in a block on the left side of the graph area.

![image](https://cloud.githubusercontent.com/assets/168669/26553877/d6506efa-448d-11e7-9c4a-2105c4b7b192.png)

**Expected behavior**
It should display correctly as it's the case with Chrome.
![image](https://cloud.githubusercontent.com/assets/168669/26553899/f2c7b34a-448d-11e7-8423-9828fb14e813.png)

**Reproduction of the problem**
Open the demo graph (https://swimlane.github.io/ngx-charts-dag/) using IE11 or Edge.

**What is the motivation / use case for changing the behavior?**
There are people using IE/Edge (yes, they do still exist :))

**Please tell us about your environment:**
Windows 10 Creator's update

* **ngx-charts version:** 2.0.0

* **Angular version:** 4.1.2

* **Browser:** [ IE 11 | Edge ]

* **Language:** [ all ]

**Comment by Gimly** [comment]
The issue seems to be coming from the fact that IE11 and later doesn't support SVG transforms through the CSS transform property, which every other browser does... See this https://connect.microsoft.com/IE/feedback/details/811744/ie11-bug-with-implementation-of-css-transforms-in-svg.

Could be that simply replacing the `[style.transform]` to `[attr.transform]` on the node could fix the issue.

**Comment by sergiobrr** [comment]
Hello, could you please provide some more info about this?
I'm having the same issue related to Edge too. 
Do you mean explicitly adding the [attr.transform]="node.options.transform" in the node template?
Something like?:

                   `<ng-template #nodeTemplate let-node>
                            <svg:g class="node"
                                    ngx-tooltip
                                    [tooltipPlacement]="'top'"
                                    [tooltipType]="'tooltip'"
                                    [tooltipTitle]="node.label">
                                <svg:rect [attr.width]="node.width" 
                                        [attr.height]="node.height" 
                                        [attr.fill]="node.options.color" />
                                <svg:text alignment-baseline="central" 
                                        [attr.x]="10" [attr.y]="node.height / 2">
                                        {{node.label}}
                                </svg:text>
                            </svg:g>
                        </ng-template>`

**Comment by Gimly** [comment]
yes, that's what I had in mind, but I've just tried and it doesn't seem to be working, it just doesn't display the transform attribute on the `svg:g` for reasons I don't get yet.

If I change it to `[attr.transform]="'rotate(45 50 50)'"` it works fine and the nodes are rotated a bit, but it doesn't seem to understand the `"node.options.transform"` for reasons I don't get.

**Comment by Gimly** [comment]
I've figured it out, sending a Pull request in a few minutes :)

**Comment by Gimly** [comment]
@marjan-georgiev Is there something missing or that I should correct for you to accept the PR? I see that there are 2 of 9 tasks complete, but not sure what those tasks are.

**Comment by nicosaliagas** [comment]
> @marjan-georgiev Is there something missing or that I should correct for you to accept the PR? I see that there are 2 of 9 tasks complete, but not sure what those tasks are.

This issue is still present, did you achieve to solve it ?
Let us know thanks !
