### ISSUE TITLE
Chrome 59 on Windows crashes - both 32 and 64 bit

### ISSUE THREAD

**Issue by sergiobrr** [swimlane/ngx-charts-dag#16]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here
```

**Current behavior**
Chrome 59.0.3071.109 32 bit and 64 bit version - crashes loading the demo page.

**Reproduction of the problem**
Go on the demo page https://swimlane.github.io/ngx-charts-dag/ with chrome 59 and it will crash

**Please tell us about your environment:**
It happens both with 32 and 64 bit versions. 

![image](https://user-images.githubusercontent.com/6337160/27530907-dfdff57a-5a5a-11e7-8667-4e3a8503c1e9.png)

**Comment by Gimly** [comment]
It seems to be somehow linked to the animations, on my project it only crashes after editing the graph, the animations are not triggered when the graph is first shown and it displays correctly.

**Comment by anvial** [comment]
Chrome 60.0.3112.78 (64 bit) - the same problem.

**Comment by Darkheir** [comment]
Same with Opera 47. It was working with Opera 45.

**Comment by Hypercubed** [comment]
Should be fixed now....  please reopen if you still see this on the demo page.

**Comment by Gimly** [comment]
What was the issue? Is it fixed with a new version?

**Comment by Hypercubed** [comment]
I believe it was a bad build and deploy.  The latest version bumped the devDeps and redepolyed... There were no functional changes.
