### ISSUE TITLE
Publish to npm please

### ISSUE THREAD

**Issue by isaacplmann** [swimlane/ngx-charts-dag#27]
I'd like to use the autoZoom feature, but it hasn't been published to npm.

Publish, please. 📦 ➡️ 💻  👏 🎉 😄

**Comment by isaacplmann** [comment]
I'd like to use this with angular 5.  Fixed by the PR #30 that you merged yesterday. @marjan-georgiev, @amcdnl please publish a new version to npm.

**Comment by kenisteward** [comment]
@marjan-georgiev I second this. I would like to build for angular 5 using this as well  👍

**Comment by kenisteward** [comment]
@marjan-georgiev Any news on this?  Is there something holding this up?

**Comment by isaacplmann** [comment]
@amcdnl @marjan-georgiev @Hypercubed can anyone shed some light on the npm publish schedule?

**Comment by marjan-georgiev** [comment]
Published 3.0.0.
