### ISSUE TITLE
I can help maintain

### ISSUE THREAD

**Issue by isaacplmann** [swimlane/ngx-charts-dag#31]
**I'm submitting a ...**  (check one with "x")
```
[x] offer to help
```

It seems like this project has moved down your priority list. I'm willing to help maintain it if you want to give me rights to do that.  If you don't want to give me those rights, let me know how else I can help.

**Comment by marjan-georgiev** [comment]
Hey Isaac,

Absolutely, any help would be appreciated. We have plans for this project, and an idea of a direction we would like to take it into, which I hope aligns with your expectations out of it.

We would like to make this a generic graph visualization tool, with an API that allows you to choose (or possibly define your own) graph layouts. In addition to the dagre layout, we would like to add support for tree and force-directed layouts, as well as structured ones (like circle, grid). That would allow use to visualize different types of graphs and trees, and allow for more customization and use cases.

Take a look at some of the features we've discussed over here with @JoshSchoen https://github.com/swimlane/ngx-charts-dag/issues/31

If this direction is in line with your idea for the project, please reach out on gitter and let's chat.

**Comment by isaacplmann** [comment]
Great! I'm on vacation until Monday. I'll reach out then.
