### ISSUE TITLE
Problem with hiphens in links id

### ISSUE THREAD

**Issue by sergiobrr** [swimlane/ngx-charts-dag#5]
Pretty sure it's not a ngx-charts-dag problem but with hiphens in links id (like UUID) it dont works: error is: 
EXCEPTION: Cannot read property 'line' of undefined

Example: 
"links": [
            {
                "source": "045dc1d0-f021-4a0b-a40b-a0d9557ddbf8",
                "target": "4ae4d2b6-64ce-4c5b-957e-20f8f1b98354"
            },
            {
                "source": "045dc1d0-f021-4a0b-a40b-a0d9557ddbf8",
                "target": "94d5a98e-7c36-45d8-8dc8-fea9e3562814"
            },
            {
                "source": "b8a18149-5ed5-43a3-b3f6-805e4bd3f43c",
                "target": "93f877ee-f41c-458d-ac50-5b0460b64b3b"
            },
            {
                "source": "4ae4d2b6-64ce-4c5b-957e-20f8f1b98354",
                "target": "b8a18149-5ed5-43a3-b3f6-805e4bd3f43c"
            },
            {
                "source": "94d5a98e-7c36-45d8-8dc8-fea9e3562814",
                "target": "93f877ee-f41c-458d-ac50-5b0460b64b3b"
            }
        ]

Replacing hiphens it works.

**Comment by marjan-georgiev** [comment]
Yes, hyphens cause problems because the dagre layout concats the ids of source and target when generating the edges, and joins then using a hyphen, which we then use to split on. The work around for now would be not to use it in IDs.

**Comment by amcdnl** [comment]
We are planning to fork dagre in the near future.

**Comment by sergiobrr** [comment]
I imagined something similar. 
Thank for the great job - i'm closing the issue.

**Comment by sweeneki** [comment]
Seems forward slashes are also a problem "/"
